CREATE TABLE students(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80),
    class VARCHAR(80)
);

INSERT INTO students (name, class)
VALUES
-- BADCAT:
('Adam', 'badcat'),
('Alexandra', 'badcat'),
('Andris', 'badcat'),
('Balint', 'badcat'),
('Bandi', 'badcat'),
('Bela', 'badcat'),
('Emese', 'badcat'),
('Fruzsi', 'badcat'),
('Hedi', 'badcat'),
('Kinga', 'badcat'),
('Laci', 'badcat'),
('MG', 'badcat'),
('Miki', 'badcat'),
('Nandi', 'badcat'),
('Tamas', 'badcat'),
('Patrik', 'badcat'),
('Rudi', 'badcat'),
-- ASBEST:
('Andras', 'asbest'),
('Anett', 'asbest'),
('Balint', 'asbest'),
('Dani', 'asbest'),
('David', 'asbest'),
('Eszti', 'asbest'),
('Marci', 'asbest'),
('Mark', 'asbest'),
('Misi', 'asbest'),
('Nori', 'asbest'),
('Nyina', 'asbest'),
('Szabolcs', 'asbest'),
('Szilard', 'asbest'),
('Tamas', 'asbest'),
('Zsuzska', 'asbest'),
-- PLEASE:
('Adam', 'please'),
('Adel', 'please'),
('Annie', 'please'),
('Balazs', 'please'),
('Balint', 'please'),
('Barni', 'please'),
('Bence', 'please'),
('Doki', 'please'),
('Fabrizio', 'please'),
('Feri', 'please'),
('Hieu', 'please'),
('Lilla', 'please'),
('Merlin', 'please'),
('Sophie', 'please'),
('Tamas', 'please'),
('Tung', 'please');
