CREATE TABLE students(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    student_name VARCHAR(80),
    student_class VARCHAR(80),
    -- student_gender VARCHAR(10),
);

INSERT INTO students (student_name, student_class)
VALUES
-- BADCAT:
('Ádám', 'badcat'),
('Alexandra', 'badcat'),
('Andris', 'badcat'),
('Bálint', 'badcat'),
('Bandi', 'badcat'),
('Béla', 'badcat'),
('Emese', 'badcat'),
('Fruzsi', 'badcat'),
('Hédi', 'badcat'),
('Kinga', 'badcat'),
('Laci', 'badcat'),
('MG', 'badcat'),
('Miki', 'badcat'),
('Nándi', 'badcat'),
('Tamás', 'badcat'),
('Patrik', 'badcat'),
('Rudi', 'badcat'),
-- ASBEST:
('András', 'asbest'),
('Anett', 'asbest'),
('Bálint', 'asbest'),
('Dani', 'asbest'),
('Dávid', 'asbest'),
('Eszti', 'asbest'),
('Marci', 'asbest'),
('Márk', 'asbest'),
('Misi', 'asbest'),
('Nóri', 'asbest'),
('Nyina', 'asbest'),
('Szabolcs', 'asbest'),
('Szilárd', 'asbest'),
('Tamás', 'asbest'),
('Zsuzska', 'asbest'),
-- PLEASE:
('Ádám', 'please'),
('Adél', 'please'),
('Annie', 'please'),
('Balázs', 'please'),
('Bálint', 'please'),
('Barni', 'please'),
('Bence', 'please'),
('Doki', 'please'),
('Fabrizio', 'please'),
('Feri', 'please'),
('Hieu', 'please'),
('Lilla', 'please'),
('Merlin', 'please'),
('Sophie', 'please'),
('Tamás', 'please'),
('Tung', 'please');
